version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pinkyuser
      POSTGRES_PASSWORD: pinkypassword
      POSTGRES_DB: pinkybar
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pinkyBar/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pinkyuser -d pinkybar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./pinkyBar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pinkybar
      SPRING_DATASOURCE_USERNAME: pinkyuser
      SPRING_DATASOURCE_PASSWORD: pinkypassword
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./pinkyBar-front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  db-data: